"""add_privacy_models

Revision ID: 114e772d2ea3
Revises: a1b2c3d4e5f6
Create Date: 2026-05-21 20:53:00.060204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '114e772d2ea3'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('privacy_audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('privacy_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_privacy_audit_logs_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_privacy_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_privacy_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('privacy_preferences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('store_reply_original_messages', sa.Boolean(), nullable=False),
    sa.Column('store_message_snippets', sa.Boolean(), nullable=False),
    sa.Column('store_calendar_titles', sa.Boolean(), nullable=False),
    sa.Column('store_task_descriptions', sa.Boolean(), nullable=False),
    sa.Column('redact_sensitive_metadata', sa.Boolean(), nullable=False),
    sa.Column('retention_days_reply_drafts', sa.Integer(), nullable=True),
    sa.Column('retention_days_messages', sa.Integer(), nullable=True),
    sa.Column('retention_days_calendar_events', sa.Integer(), nullable=True),
    sa.Column('retention_days_llm_usage_logs', sa.Integer(), nullable=True),
    sa.Column('allow_usage_analytics', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('privacy_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_privacy_preferences_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('privacy_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_privacy_preferences_user_id'))

    op.drop_table('privacy_preferences')
    with op.batch_alter_table('privacy_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_privacy_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_privacy_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_privacy_audit_logs_action_type'))

    op.drop_table('privacy_audit_logs')
    # ### end Alembic commands ###
