"""add_llm_usage_logs

Revision ID: 1cf054a14e41
Revises: d011b98989eb
Create Date: 2026-05-19 00:08:23.903245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cf054a14e41'
down_revision: Union[str, Sequence[str], None] = 'd011b98989eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_usage_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('feature', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('request_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_usage_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_usage_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_llm_usage_logs_provider', ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_usage_logs_status'), ['status'], unique=False)
        batch_op.create_index('ix_llm_usage_logs_user_feature', ['user_id', 'feature'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_usage_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_llm_usage_logs_user_status', ['user_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_usage_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_llm_usage_logs_user_status')
        batch_op.drop_index(batch_op.f('ix_llm_usage_logs_user_id'))
        batch_op.drop_index('ix_llm_usage_logs_user_feature')
        batch_op.drop_index(batch_op.f('ix_llm_usage_logs_status'))
        batch_op.drop_index('ix_llm_usage_logs_provider')
        batch_op.drop_index(batch_op.f('ix_llm_usage_logs_created_at'))

    op.drop_table('llm_usage_logs')
    # ### end Alembic commands ###
