"""baseline_day5

Revision ID: a32cab471b2a
Revises: 
Create Date: 2026-05-17 00:06:48.541436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a32cab471b2a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('preferred_tone', sa.String(), nullable=False),
    sa.Column('max_reply_length', sa.String(), nullable=False),
    sa.Column('peak_energy_hours', sa.JSON(), nullable=False),
    sa.Column('low_energy_hours', sa.JSON(), nullable=False),
    sa.Column('sensory_triggers', sa.JSON(), nullable=False),
    sa.Column('recovery_preferences', sa.JSON(), nullable=False),
    sa.Column('transition_support_needed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('estimated_energy', sa.String(), nullable=True),
    sa.Column('estimated_sensory_cost', sa.String(), nullable=True),
    sa.Column('last_touched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_user_id'), ['user_id'], unique=False)

    op.create_table('micro_actions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('plan_id', sa.String(), nullable=True),
    sa.Column('parent_micro_action_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('energy_cost', sa.String(), nullable=True),
    sa.Column('sensory_cost', sa.String(), nullable=True),
    sa.Column('friction_level', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('micro_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_micro_actions_user_id'), ['user_id'], unique=False)

    op.create_table('copilot_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('generated_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('copilot_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_copilot_plans_user_id'), ['user_id'], unique=False)

    op.create_table('energy_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('battery_level', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('sensory_state', sa.String(), nullable=False),
    sa.Column('mood', sa.String(), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('energy_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_energy_logs_user_id'), ['user_id'], unique=False)

    op.create_table('transition_scripts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('transition_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('script_steps', sa.JSON(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('tone', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('success_rating', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transition_scripts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transition_scripts_transition_type'), ['transition_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_transition_scripts_user_id'), ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transition_scripts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transition_scripts_user_id'))
        batch_op.drop_index(batch_op.f('ix_transition_scripts_transition_type'))
    op.drop_table('transition_scripts')

    with op.batch_alter_table('energy_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_energy_logs_user_id'))
    op.drop_table('energy_logs')

    with op.batch_alter_table('copilot_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_copilot_plans_user_id'))
    op.drop_table('copilot_plans')

    with op.batch_alter_table('micro_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_micro_actions_user_id'))
    op.drop_table('micro_actions')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_user_id'))
    op.drop_table('tasks')

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profiles_user_id'))
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
