"""baseline_day5

Revision ID: a32cab471b2a
Revises: 
Create Date: 2026-05-17 00:06:48.541436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a32cab471b2a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transition_scripts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('transition_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('script_steps', sa.JSON(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('tone', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('success_rating', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transition_scripts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transition_scripts_transition_type'), ['transition_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_transition_scripts_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('micro_actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_micro_action_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('micro_actions', schema=None) as batch_op:
        batch_op.drop_column('parent_micro_action_id')

    with op.batch_alter_table('transition_scripts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transition_scripts_user_id'))
        batch_op.drop_index(batch_op.f('ix_transition_scripts_transition_type'))

    op.drop_table('transition_scripts')
    # ### end Alembic commands ###
