"""add_reply_drafts

Revision ID: d011b98989eb
Revises: a32cab471b2a
Create Date: 2026-05-18 23:52:03.681321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd011b98989eb'
down_revision: Union[str, Sequence[str], None] = 'a32cab471b2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reply_drafts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('original_message', sa.Text(), nullable=False),
    sa.Column('message_sender', sa.String(), nullable=True),
    sa.Column('message_subject', sa.String(), nullable=True),
    sa.Column('message_channel', sa.String(), nullable=False),
    sa.Column('user_intent', sa.Text(), nullable=True),
    sa.Column('preferred_tone', sa.String(), nullable=True),
    sa.Column('context_note', sa.Text(), nullable=True),
    sa.Column('draft_options', sa.JSON(), nullable=False),
    sa.Column('selected_option_type', sa.String(), nullable=True),
    sa.Column('edited_reply', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reply_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reply_drafts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reply_drafts_status'), ['status'], unique=False)
        batch_op.create_index('ix_reply_drafts_user_channel', ['user_id', 'message_channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_reply_drafts_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reply_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reply_drafts_user_id'))
        batch_op.drop_index('ix_reply_drafts_user_channel')
        batch_op.drop_index(batch_op.f('ix_reply_drafts_status'))
        batch_op.drop_index(batch_op.f('ix_reply_drafts_created_at'))

    op.drop_table('reply_drafts')
    # ### end Alembic commands ###
