"""add_calendar_and_overload_events

Revision ID: f0fae2c4efa4
Revises: 1cf054a14e41
Create Date: 2026-05-20 20:17:47.327371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0fae2c4efa4'
down_revision: Union[str, Sequence[str], None] = '1cf054a14e41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('external_event_id', sa.String(), nullable=True),
    sa.Column('calendar_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('attendee_count', sa.Integer(), nullable=False),
    sa.Column('meeting_type', sa.String(), nullable=False),
    sa.Column('load_score', sa.Integer(), nullable=False),
    sa.Column('energy_cost', sa.String(), nullable=False),
    sa.Column('sensory_cost', sa.String(), nullable=False),
    sa.Column('is_back_to_back', sa.Boolean(), nullable=False),
    sa.Column('is_busy', sa.Boolean(), nullable=False),
    sa.Column('raw_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.create_index('idx_user_provider_ext_event_id', ['user_id', 'provider', 'external_event_id'], unique=True)
        batch_op.create_index('idx_user_start_time', ['user_id', 'start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_is_back_to_back'), ['is_back_to_back'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_meeting_type'), ['meeting_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_user_id'), ['user_id'], unique=False)

    op.create_table('overload_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('trigger_reasons', sa.JSON(), nullable=False),
    sa.Column('energy_score', sa.Integer(), nullable=True),
    sa.Column('calendar_load_score', sa.Integer(), nullable=True),
    sa.Column('open_task_count', sa.Integer(), nullable=True),
    sa.Column('high_priority_task_count', sa.Integer(), nullable=True),
    sa.Column('stuck_task_count', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('overload_events', schema=None) as batch_op:
        batch_op.create_index('idx_user_detected_at', ['user_id', 'detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_overload_events_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('overload_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_overload_events_user_id'))
        batch_op.drop_index('idx_user_detected_at')

    op.drop_table('overload_events')
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_start_time'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_meeting_type'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_is_back_to_back'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_end_time'))
        batch_op.drop_index('idx_user_start_time')
        batch_op.drop_index('idx_user_provider_ext_event_id')

    op.drop_table('calendar_events')
    # ### end Alembic commands ###
